export PYENV_ROOT=${OPENSHIFT_DATA_DIR}pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"

export XDG_CACHE_HOME=${OPENSHIFT_DATA_DIR}  # for pip cache
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
export LC_LANG='en_US.UTF-8'
